# docker-compose.yml
version: "3.7"
services:
  webapp:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: example